// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    AList: typeof import('@arco-design/web-vue')['List']
    AListItem: typeof import('@arco-design/web-vue')['ListItem']
    ASlider: typeof import('@arco-design/web-vue')['Slider']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    'IMdi:close': typeof import('~icons/mdi/close')['default']
    'IMdi:windowMaximize': typeof import('~icons/mdi/window-maximize')['default']
    'IMdi:windowMinimize': typeof import('~icons/mdi/window-minimize')['default']
    'IMdi:windowRestore': typeof import('~icons/mdi/window-restore')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TitleBar: typeof import('./src/components/app/TitleBar.vue')['default']
  }
}
