// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFile(arg1) {
  return window['go']['file']['FileReader']['GetFile'](arg1);
}

export function GetFileManga() {
  return window['go']['file']['FileReader']['GetFileManga']();
}
