// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetManga(arg1:string):Promise<models.Manga>;

export function GetMangaHome(arg1:number,arg2:number):Promise<models.MangaHome>;

export function GetMangas():Promise<Array<models.Manga>>;

export function GetPage(arg1:number):Promise<any>;
