// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetManga(arg1) {
  return window['go']['manga']['Manga']['GetManga'](arg1);
}

export function GetMangaHome(arg1, arg2) {
  return window['go']['manga']['Manga']['GetMangaHome'](arg1, arg2);
}

export function GetMangas() {
  return window['go']['manga']['Manga']['GetMangas']();
}

export function GetPage(arg1) {
  return window['go']['manga']['Manga']['GetPage'](arg1);
}
