// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apps} from '../models';

export function ConnectDatabasePostgres(arg1:string):Promise<void>;

export function ConnectDatabaseSqlite(arg1:string):Promise<void>;

export function Find(arg1:string,arg2:Array<string>):Promise<Array<string>>;

export function GetManga():Promise<Array<apps.Manga>>;

export function Greet(arg1:string):Promise<string>;
