// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {runtime} from '../models';

export function ConnectDatabasePostgres(arg1:string):Promise<void>;

export function ConnectDatabaseSqlite(arg1:string):Promise<void>;

export function Find(arg1:string,arg2:Array<string>):Promise<Array<string>>;

export function GetENV():Promise<runtime.EnvironmentInfo>;

export function GetUserDataPath():Promise<string>;

export function Greet(arg1:string):Promise<string>;
