// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectDatabasePostgres(arg1) {
  return window['go']['apps']['App']['ConnectDatabasePostgres'](arg1);
}

export function ConnectDatabaseSqlite(arg1) {
  return window['go']['apps']['App']['ConnectDatabaseSqlite'](arg1);
}

export function Find(arg1, arg2) {
  return window['go']['apps']['App']['Find'](arg1, arg2);
}

export function GetManga() {
  return window['go']['apps']['App']['GetManga']();
}

export function Greet(arg1) {
  return window['go']['apps']['App']['Greet'](arg1);
}
