// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Find(arg1:string,arg2:Array<string>):Promise<Array<string>>;

export function GetManga():Promise<Array<main.Manga>>;

export function Greet(arg1:string):Promise<string>;
